### ISSUE TITLE
MVP V1

### ISSUE THREAD

**Issue by fritzschoff** [cangurel90/uniswap_lp_roi#18]
# Features:
- [x] Make Web3 provider connections mandatory to see results.
- [x] Prepare payment possibilities: add key to DB `payed:boolean`   
- [x] Use expansion panels for 1. Pool information, 2. User input 3. Results (hide if not connected to web3)
- [x] Search by tokens: have two inputs with autocompletion. 
- [x] Search by pool address  
- [x] Toggle button to determine how the user want to query pool information
- [x] Implement the sub graph from uniswap v2
- [x] parse new data from API
- [x] Calculate token price in usd : `reserveUSD / 2 / reserve0 | reserve1`
 
## Optional
- [x] write nodejs script for Can to keep the database up to date if we can't query by erc20 symbols from the graph

# Old issues:
- [x] it would be better if link pointed to uniswap.info instead of Etherscan, ex link for wbtc-eth https://uniswap.info/pair/0xbb2b8038a1640196fbe3e38816f3e67cba72d940
- [x] If users input exceeds the max amount for token price for instance, set the input to the max possible value and open up snackbar: Max value is etc...
- [x] n sliders lets use "M" for million, and "K" for thousand
- [x] Can you replace HOLD Token and HODL Token2 with their respective names in the table
- [x] add delay to user input to recalculate for sliders and inputs
